import ThreadDetail from 'components/ThreadDetail'
import type { NextPage } from 'next'
import Head from 'next/head'
import { fetchThread } from 'services/reddit'
import styled from 'styled-components'
import { Thread } from 'types/thread'

const Wrapper = styled.div``

const Main = styled.main`
  padding: 20px;
`

interface ThreadPageProps {
  thread: Thread
}

const ThreadPage: NextPage<ThreadPageProps> = (props) => {
  const { thread } = props
  return (
    <Wrapper>
      <Head>
        <title>Thread Listing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <ThreadDetail thread={thread}/>
      </Main>
    </Wrapper>
  )
}

ThreadPage.getInitialProps = async ({ query }) => {
  const result = await fetchThread(query.slug as string)
  return {
    thread: result
  }
}

export default ThreadPage
